language: ruby

bundler_args: '--with=development --jobs=3 --retry=3 --verbose'

rvm:
  - 2.2.4

sudo: required

cache:
  bundler: true

git:
  depth: 15

notifications:
  email: false
  # slack: some_org:some_api_key

addons:
  hosts:
    - 'localhost'
    - 'shared-platform.test'
  # code_climate:
  #   repo_token: some_secret_token
  postgresql: '10.4'

services:
  - mongodb
  - postgresql
  - rabbitmq
  - redis-server

# before_install:
#   - 'gem install travis && (bin/travis-dedup $TRAVIS_REPO_SLUG $TRAVIS_ACCESS_TOKEN &)'

script: bin/travis-runner

matrix:
  fast_finish: true

env:
  global:
    # Secured: GITHUB_OAUTH_TOKEN, TRAVIS_ACCESS_TOKEN
    - secure: "hLtqvxFyuxHrb0T1n7eg4+IxVSk8V6Tt4RgC4FI0NWdIz2GwTCICCgIBk4i+rHUX5Jb9T58IBpiXA2VTQhs5XGt52OHk//jYRTA/zLc7M1zVDLyr079iUY3xUj1w1i0c9xmVezRmz4bFJspV3IHMwa5ZoWuRdniBuge3wLQkM4KPZI7+3tYCJGbwW0QmMokrU18MEGE9s1Iq7AYdiTPYE7SaQ3H/uYc1+Y3CNFfWPIdfZFqHqpVM7bJox6IzxLkCjHmWWsmeVWl11CEtpOpIiAJX0oIFPWwOTwdQMDyoVQfVNuEZQ2BVdKiVktVoCLpbOSfQ0ExaQS/BvJ7Y9ncXIzyze8ij2NXBpUcVGfY7BtrmJpIKvsRwy8XVPPryHHvcpv+s99FsyyqW91XJH+Dran7RrVUaeFTMtY1rmyvcSouCwY/ovedJXEHbjMaH+29RuNerFqjQ6GTGvXoAfRSzTcLLpfzcUdFPObrbYi0BUMpNWRnVnZbCULPxdcv+byYwJBkH4XgU29auN6Lx+Qa/hAlX/ZPFDWdYtUFFYRdndLihHwg4jEnO4u0CNOl6VcNy87nuHSMMA8cMDIqijyog5iPRbuJzItK+VJmGJuVIUUBYo678btYCnIlozudq2M4e7hS6FZxy+MUvi/QjYCJZiDxRRnCVfP/4IP5E4vcRPrU="
    # - RABBITMQ_VERSION=3.4.3
  matrix:
  - RAILS_ENV=linting RAKE_TASK=linters:all
  - RAILS_ENV=test    RSPEC_SUITE=spec/     INSTALL_DEPS=false
