nonsecure: &nonsecure
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] ||= 'a6a0fa35d62a1056fbca9596db9c79aed4e2c0656ef0924b7cfe66d0333f9346cf10c1fed613cebb3fbedb4a9c165d96095c3a4d7021be17d77a22f78c8d8374' %>

development:
  <<: *nonsecure

test:
  <<: *nonsecure

linting:
  <<: *nonsecure

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
