development:
  handle:   'public'
  host:     'shared-platform.test'
  email:    'administrator@shared-platform.test'
  password: 'administrator'
  api_key:  'd49cd50f6f0d2b163f48fc73cb249f0244c37074'

test:
  handle:   'public'
  host:     'localhost:39875'
  email:    'administrator@shared-platform.test'
  password: 'administrator'
  api_key:  'd49cd50f6f0d2b163f48fc73cb249f0244c37074'

# staging:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
#   # ssl: true

# production:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
#   # ssl: true
